In [1]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure, show, output_file

In [2]:
start = datetime.datetime(2017, 11, 1)
end = datetime.datetime(2018, 2, 1)

df = data.DataReader(name="GOOG", data_source="yahoo", start=start, end=end)
df

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Close</th>
      <th>Adj Close</th>
      <th>Volume</th>
    </tr>
    <tr>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2017-10-31</th>
      <td>1015.219971</td>
      <td>1024.000000</td>
      <td>1010.419983</td>
      <td>1016.640015</td>
      <td>1016.640015</td>
      <td>1330700</td>
    </tr>
    <tr>
      <th>2017-11-01</th>
      <td>1017.210022</td>
      <td>1029.670044</td>
      <td>1016.950012</td>
      <td>1025.500000</td>
      <td>1025.500000</td>
      <td>1373400</td>
    </tr>
    <tr>
      <th>2017-11-02</th>
      <td>1021.760010</td>
      <td>1028.089966</td>
      <td>1013.010010</td>
      <td>1025.579956</td>
      <td>1025.579956</td>
      <td>1049000</td>
    </tr>
    <tr>
      <th>2017-11-03</th>
      <td>1022.109985</td>
      <td>1032.650024</td>
      <td>1020.309998</td>
      <td>1032.479980</td>
      <td>1032.479980</td>
      <td>1076400</td>
    </tr>
    <tr>
      <th>2017-11-06</th>
      <td>1028.989990</td>
      <td>1034.869995</td>
      <td>1025.000000</td>
      <td>1025.900024</td>
      <td>1025.900024</td>
      <td>1125200</td>
    </tr>
    <tr>
      <th>2017-11-07</th>
      <td>1027.270020</td>
      <td>1033.969971</td>
      <td>1025.130005</td>
      <td>1033.329956</td>
      <td>1033.329956</td>
      <td>1112300</td>
    </tr>
    <tr>
      <th>2017-11-08</th>
      <td>1030.520020</td>
      <td>1043.521973</td>
      <td>1028.449951</td>
      <td>1039.849976</td>
      <td>1039.849976</td>
      <td>1088700</td>
    </tr>
    <tr>
      <th>2017-11-09</th>
      <td>1033.989990</td>
      <td>1033.989990</td>
      <td>1019.666016</td>
      <td>1031.260010</td>
      <td>1031.260010</td>
      <td>1245200</td>
    </tr>
    <tr>
      <th>2017-11-10</th>
      <td>1026.459961</td>
      <td>1030.760010</td>
      <td>1025.280029</td>
      <td>1028.069946</td>
      <td>1028.069946</td>
      <td>720000</td>
    </tr>
    <tr>
      <th>2017-11-13</th>
      <td>1023.419983</td>
      <td>1031.579956</td>
      <td>1022.570007</td>
      <td>1025.750000</td>
      <td>1025.750000</td>
      <td>885800</td>
    </tr>
    <tr>
      <th>2017-11-14</th>
      <td>1022.590027</td>
      <td>1026.810059</td>
      <td>1014.150024</td>
      <td>1026.000000</td>
      <td>1026.000000</td>
      <td>959200</td>
    </tr>
    <tr>
      <th>2017-11-15</th>
      <td>1019.210022</td>
      <td>1024.089966</td>
      <td>1015.419983</td>
      <td>1020.909973</td>
      <td>1020.909973</td>
      <td>854000</td>
    </tr>
    <tr>
      <th>2017-11-16</th>
      <td>1022.520020</td>
      <td>1035.920044</td>
      <td>1022.520020</td>
      <td>1032.500000</td>
      <td>1032.500000</td>
      <td>1129700</td>
    </tr>
    <tr>
      <th>2017-11-17</th>
      <td>1034.010010</td>
      <td>1034.420044</td>
      <td>1017.750000</td>
      <td>1019.090027</td>
      <td>1019.090027</td>
      <td>1397100</td>
    </tr>
    <tr>
      <th>2017-11-20</th>
      <td>1020.260010</td>
      <td>1022.609985</td>
      <td>1017.500000</td>
      <td>1018.380005</td>
      <td>1018.380005</td>
      <td>953500</td>
    </tr>
    <tr>
      <th>2017-11-21</th>
      <td>1023.309998</td>
      <td>1035.109985</td>
      <td>1022.655029</td>
      <td>1034.489990</td>
      <td>1034.489990</td>
      <td>1097000</td>
    </tr>
    <tr>
      <th>2017-11-22</th>
      <td>1035.000000</td>
      <td>1039.706055</td>
      <td>1031.430054</td>
      <td>1035.959961</td>
      <td>1035.959961</td>
      <td>746300</td>
    </tr>
    <tr>
      <th>2017-11-24</th>
      <td>1035.869995</td>
      <td>1043.177979</td>
      <td>1035.000000</td>
      <td>1040.609985</td>
      <td>1040.609985</td>
      <td>537000</td>
    </tr>
    <tr>
      <th>2017-11-27</th>
      <td>1040.000000</td>
      <td>1055.459961</td>
      <td>1038.439941</td>
      <td>1054.209961</td>
      <td>1054.209961</td>
      <td>1307900</td>
    </tr>
    <tr>
      <th>2017-11-28</th>
      <td>1055.089966</td>
      <td>1062.375000</td>
      <td>1040.000000</td>
      <td>1047.410034</td>
      <td>1047.410034</td>
      <td>1424400</td>
    </tr>
    <tr>
      <th>2017-11-29</th>
      <td>1042.680054</td>
      <td>1044.079956</td>
      <td>1015.650024</td>
      <td>1021.659973</td>
      <td>1021.659973</td>
      <td>2459400</td>
    </tr>
    <tr>
      <th>2017-11-30</th>
      <td>1022.369995</td>
      <td>1028.489990</td>
      <td>1015.000000</td>
      <td>1021.409973</td>
      <td>1021.409973</td>
      <td>1724000</td>
    </tr>
    <tr>
      <th>2017-12-01</th>
      <td>1015.799988</td>
      <td>1022.489990</td>
      <td>1002.020020</td>
      <td>1010.169983</td>
      <td>1010.169983</td>
      <td>1909600</td>
    </tr>
    <tr>
      <th>2017-12-04</th>
      <td>1012.659973</td>
      <td>1016.099976</td>
      <td>995.570007</td>
      <td>998.679993</td>
      <td>998.679993</td>
      <td>1906400</td>
    </tr>
    <tr>
      <th>2017-12-05</th>
      <td>995.940002</td>
      <td>1020.609985</td>
      <td>988.280029</td>
      <td>1005.150024</td>
      <td>1005.150024</td>
      <td>2067300</td>
    </tr>
    <tr>
      <th>2017-12-06</th>
      <td>1001.500000</td>
      <td>1024.969971</td>
      <td>1001.140015</td>
      <td>1018.380005</td>
      <td>1018.380005</td>
      <td>1272000</td>
    </tr>
    <tr>
      <th>2017-12-07</th>
      <td>1020.429993</td>
      <td>1034.239990</td>
      <td>1018.070984</td>
      <td>1030.930054</td>
      <td>1030.930054</td>
      <td>1458200</td>
    </tr>
    <tr>
      <th>2017-12-08</th>
      <td>1037.489990</td>
      <td>1042.050049</td>
      <td>1032.521973</td>
      <td>1037.050049</td>
      <td>1037.050049</td>
      <td>1290800</td>
    </tr>
    <tr>
      <th>2017-12-11</th>
      <td>1035.500000</td>
      <td>1043.800049</td>
      <td>1032.050049</td>
      <td>1041.099976</td>
      <td>1041.099976</td>
      <td>1192800</td>
    </tr>
    <tr>
      <th>2017-12-12</th>
      <td>1039.630005</td>
      <td>1050.310059</td>
      <td>1033.689941</td>
      <td>1040.479980</td>
      <td>1040.479980</td>
      <td>1279500</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2017-12-19</th>
      <td>1075.199951</td>
      <td>1076.839966</td>
      <td>1063.550049</td>
      <td>1070.680054</td>
      <td>1070.680054</td>
      <td>1338700</td>
    </tr>
    <tr>
      <th>2017-12-20</th>
      <td>1071.780029</td>
      <td>1073.380005</td>
      <td>1061.520020</td>
      <td>1064.949951</td>
      <td>1064.949951</td>
      <td>1268600</td>
    </tr>
    <tr>
      <th>2017-12-21</th>
      <td>1064.949951</td>
      <td>1069.329956</td>
      <td>1061.793945</td>
      <td>1063.630005</td>
      <td>1063.630005</td>
      <td>995700</td>
    </tr>
    <tr>
      <th>2017-12-22</th>
      <td>1061.109985</td>
      <td>1064.199951</td>
      <td>1059.439941</td>
      <td>1060.119995</td>
      <td>1060.119995</td>
      <td>755100</td>
    </tr>
    <tr>
      <th>2017-12-26</th>
      <td>1058.069946</td>
      <td>1060.119995</td>
      <td>1050.199951</td>
      <td>1056.739990</td>
      <td>1056.739990</td>
      <td>760600</td>
    </tr>
    <tr>
      <th>2017-12-27</th>
      <td>1057.390015</td>
      <td>1058.369995</td>
      <td>1048.050049</td>
      <td>1049.369995</td>
      <td>1049.369995</td>
      <td>1271900</td>
    </tr>
    <tr>
      <th>2017-12-28</th>
      <td>1051.599976</td>
      <td>1054.750000</td>
      <td>1044.770020</td>
      <td>1048.140015</td>
      <td>1048.140015</td>
      <td>837100</td>
    </tr>
    <tr>
      <th>2017-12-29</th>
      <td>1046.719971</td>
      <td>1049.699951</td>
      <td>1044.900024</td>
      <td>1046.400024</td>
      <td>1046.400024</td>
      <td>887500</td>
    </tr>
    <tr>
      <th>2018-01-02</th>
      <td>1048.339966</td>
      <td>1066.939941</td>
      <td>1045.229980</td>
      <td>1065.000000</td>
      <td>1065.000000</td>
      <td>1237600</td>
    </tr>
    <tr>
      <th>2018-01-03</th>
      <td>1064.310059</td>
      <td>1086.290039</td>
      <td>1063.209961</td>
      <td>1082.479980</td>
      <td>1082.479980</td>
      <td>1430200</td>
    </tr>
    <tr>
      <th>2018-01-04</th>
      <td>1088.000000</td>
      <td>1093.569946</td>
      <td>1084.001953</td>
      <td>1086.400024</td>
      <td>1086.400024</td>
      <td>1004600</td>
    </tr>
    <tr>
      <th>2018-01-05</th>
      <td>1094.000000</td>
      <td>1104.250000</td>
      <td>1092.000000</td>
      <td>1102.229980</td>
      <td>1102.229980</td>
      <td>1279100</td>
    </tr>
    <tr>
      <th>2018-01-08</th>
      <td>1102.229980</td>
      <td>1111.270020</td>
      <td>1101.619995</td>
      <td>1106.939941</td>
      <td>1106.939941</td>
      <td>1047600</td>
    </tr>
    <tr>
      <th>2018-01-09</th>
      <td>1109.400024</td>
      <td>1110.569946</td>
      <td>1101.230957</td>
      <td>1106.260010</td>
      <td>1106.260010</td>
      <td>902500</td>
    </tr>
    <tr>
      <th>2018-01-10</th>
      <td>1097.099976</td>
      <td>1104.599976</td>
      <td>1096.109985</td>
      <td>1102.609985</td>
      <td>1102.609985</td>
      <td>1042800</td>
    </tr>
    <tr>
      <th>2018-01-11</th>
      <td>1106.300049</td>
      <td>1106.525024</td>
      <td>1099.589966</td>
      <td>1105.520020</td>
      <td>1105.520020</td>
      <td>978300</td>
    </tr>
    <tr>
      <th>2018-01-12</th>
      <td>1102.410034</td>
      <td>1124.290039</td>
      <td>1101.150024</td>
      <td>1122.260010</td>
      <td>1122.260010</td>
      <td>1720500</td>
    </tr>
    <tr>
      <th>2018-01-16</th>
      <td>1132.510010</td>
      <td>1139.910034</td>
      <td>1117.832031</td>
      <td>1121.760010</td>
      <td>1121.760010</td>
      <td>1575300</td>
    </tr>
    <tr>
      <th>2018-01-17</th>
      <td>1126.219971</td>
      <td>1132.599976</td>
      <td>1117.010010</td>
      <td>1131.979980</td>
      <td>1131.979980</td>
      <td>1202600</td>
    </tr>
    <tr>
      <th>2018-01-18</th>
      <td>1131.410034</td>
      <td>1132.510010</td>
      <td>1117.500000</td>
      <td>1129.790039</td>
      <td>1129.790039</td>
      <td>1198200</td>
    </tr>
    <tr>
      <th>2018-01-19</th>
      <td>1131.829956</td>
      <td>1137.859985</td>
      <td>1128.300049</td>
      <td>1137.510010</td>
      <td>1137.510010</td>
      <td>1778200</td>
    </tr>
    <tr>
      <th>2018-01-22</th>
      <td>1137.489990</td>
      <td>1159.880005</td>
      <td>1135.109985</td>
      <td>1155.810059</td>
      <td>1155.810059</td>
      <td>1618000</td>
    </tr>
    <tr>
      <th>2018-01-23</th>
      <td>1159.849976</td>
      <td>1171.626953</td>
      <td>1158.750000</td>
      <td>1169.969971</td>
      <td>1169.969971</td>
      <td>1333100</td>
    </tr>
    <tr>
      <th>2018-01-24</th>
      <td>1177.329956</td>
      <td>1179.859985</td>
      <td>1161.050049</td>
      <td>1164.239990</td>
      <td>1164.239990</td>
      <td>1416600</td>
    </tr>
    <tr>
      <th>2018-01-25</th>
      <td>1172.530029</td>
      <td>1175.939941</td>
      <td>1162.760010</td>
      <td>1170.369995</td>
      <td>1170.369995</td>
      <td>1480500</td>
    </tr>
    <tr>
      <th>2018-01-26</th>
      <td>1175.079956</td>
      <td>1175.839966</td>
      <td>1158.109985</td>
      <td>1175.839966</td>
      <td>1175.839966</td>
      <td>2018800</td>
    </tr>
    <tr>
      <th>2018-01-29</th>
      <td>1176.479980</td>
      <td>1186.890015</td>
      <td>1171.979980</td>
      <td>1175.579956</td>
      <td>1175.579956</td>
      <td>1378900</td>
    </tr>
    <tr>
      <th>2018-01-30</th>
      <td>1167.829956</td>
      <td>1176.520020</td>
      <td>1163.520020</td>
      <td>1163.689941</td>
      <td>1163.689941</td>
      <td>1556300</td>
    </tr>
    <tr>
      <th>2018-01-31</th>
      <td>1170.569946</td>
      <td>1173.000000</td>
      <td>1159.130005</td>
      <td>1169.939941</td>
      <td>1169.939941</td>
      <td>1538700</td>
    </tr>
    <tr>
      <th>2018-02-01</th>
      <td>1162.609985</td>
      <td>1174.000000</td>
      <td>1157.520020</td>
      <td>1167.699951</td>
      <td>1167.699951</td>
      <td>2412100</td>
    </tr>
  </tbody>
</table>
<p>64 rows × 6 columns</p>
</div>

In [3]:
def inc_dec(c, o):
    if c > o:
        value="Increase"
    elif c < o:
        value="Decrease"
    else:
        value="Equal"
    return value

df["Status"]=[inc_dec(c, o) for c, o in zip(df.Close, df.Open)]

In [4]:
df["Middle"]=(df.Open+df.Close)/2
df["Height"]=abs(df.Open-df.Close)
df

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Close</th>
      <th>Adj Close</th>
      <th>Volume</th>
      <th>Status</th>
      <th>Middle</th>
      <th>Height</th>
    </tr>
    <tr>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2017-10-31</th>
      <td>1015.219971</td>
      <td>1024.000000</td>
      <td>1010.419983</td>
      <td>1016.640015</td>
      <td>1016.640015</td>
      <td>1330700</td>
      <td>Increase</td>
      <td>1015.929993</td>
      <td>1.420044</td>
    </tr>
    <tr>
      <th>2017-11-01</th>
      <td>1017.210022</td>
      <td>1029.670044</td>
      <td>1016.950012</td>
      <td>1025.500000</td>
      <td>1025.500000</td>
      <td>1373400</td>
      <td>Increase</td>
      <td>1021.355011</td>
      <td>8.289978</td>
    </tr>
    <tr>
      <th>2017-11-02</th>
      <td>1021.760010</td>
      <td>1028.089966</td>
      <td>1013.010010</td>
      <td>1025.579956</td>
      <td>1025.579956</td>
      <td>1049000</td>
      <td>Increase</td>
      <td>1023.669983</td>
      <td>3.819946</td>
    </tr>
    <tr>
      <th>2017-11-03</th>
      <td>1022.109985</td>
      <td>1032.650024</td>
      <td>1020.309998</td>
      <td>1032.479980</td>
      <td>1032.479980</td>
      <td>1076400</td>
      <td>Increase</td>
      <td>1027.294983</td>
      <td>10.369995</td>
    </tr>
    <tr>
      <th>2017-11-06</th>
      <td>1028.989990</td>
      <td>1034.869995</td>
      <td>1025.000000</td>
      <td>1025.900024</td>
      <td>1025.900024</td>
      <td>1125200</td>
      <td>Decrease</td>
      <td>1027.445007</td>
      <td>3.089966</td>
    </tr>
    <tr>
      <th>2017-11-07</th>
      <td>1027.270020</td>
      <td>1033.969971</td>
      <td>1025.130005</td>
      <td>1033.329956</td>
      <td>1033.329956</td>
      <td>1112300</td>
      <td>Increase</td>
      <td>1030.299988</td>
      <td>6.059936</td>
    </tr>
    <tr>
      <th>2017-11-08</th>
      <td>1030.520020</td>
      <td>1043.521973</td>
      <td>1028.449951</td>
      <td>1039.849976</td>
      <td>1039.849976</td>
      <td>1088700</td>
      <td>Increase</td>
      <td>1035.184998</td>
      <td>9.329956</td>
    </tr>
    <tr>
      <th>2017-11-09</th>
      <td>1033.989990</td>
      <td>1033.989990</td>
      <td>1019.666016</td>
      <td>1031.260010</td>
      <td>1031.260010</td>
      <td>1245200</td>
      <td>Decrease</td>
      <td>1032.625000</td>
      <td>2.729980</td>
    </tr>
    <tr>
      <th>2017-11-10</th>
      <td>1026.459961</td>
      <td>1030.760010</td>
      <td>1025.280029</td>
      <td>1028.069946</td>
      <td>1028.069946</td>
      <td>720000</td>
      <td>Increase</td>
      <td>1027.264954</td>
      <td>1.609985</td>
    </tr>
    <tr>
      <th>2017-11-13</th>
      <td>1023.419983</td>
      <td>1031.579956</td>
      <td>1022.570007</td>
      <td>1025.750000</td>
      <td>1025.750000</td>
      <td>885800</td>
      <td>Increase</td>
      <td>1024.584991</td>
      <td>2.330017</td>
    </tr>
    <tr>
      <th>2017-11-14</th>
      <td>1022.590027</td>
      <td>1026.810059</td>
      <td>1014.150024</td>
      <td>1026.000000</td>
      <td>1026.000000</td>
      <td>959200</td>
      <td>Increase</td>
      <td>1024.295014</td>
      <td>3.409973</td>
    </tr>
    <tr>
      <th>2017-11-15</th>
      <td>1019.210022</td>
      <td>1024.089966</td>
      <td>1015.419983</td>
      <td>1020.909973</td>
      <td>1020.909973</td>
      <td>854000</td>
      <td>Increase</td>
      <td>1020.059998</td>
      <td>1.699951</td>
    </tr>
    <tr>
      <th>2017-11-16</th>
      <td>1022.520020</td>
      <td>1035.920044</td>
      <td>1022.520020</td>
      <td>1032.500000</td>
      <td>1032.500000</td>
      <td>1129700</td>
      <td>Increase</td>
      <td>1027.510010</td>
      <td>9.979980</td>
    </tr>
    <tr>
      <th>2017-11-17</th>
      <td>1034.010010</td>
      <td>1034.420044</td>
      <td>1017.750000</td>
      <td>1019.090027</td>
      <td>1019.090027</td>
      <td>1397100</td>
      <td>Decrease</td>
      <td>1026.550019</td>
      <td>14.919983</td>
    </tr>
    <tr>
      <th>2017-11-20</th>
      <td>1020.260010</td>
      <td>1022.609985</td>
      <td>1017.500000</td>
      <td>1018.380005</td>
      <td>1018.380005</td>
      <td>953500</td>
      <td>Decrease</td>
      <td>1019.320007</td>
      <td>1.880005</td>
    </tr>
    <tr>
      <th>2017-11-21</th>
      <td>1023.309998</td>
      <td>1035.109985</td>
      <td>1022.655029</td>
      <td>1034.489990</td>
      <td>1034.489990</td>
      <td>1097000</td>
      <td>Increase</td>
      <td>1028.899994</td>
      <td>11.179992</td>
    </tr>
    <tr>
      <th>2017-11-22</th>
      <td>1035.000000</td>
      <td>1039.706055</td>
      <td>1031.430054</td>
      <td>1035.959961</td>
      <td>1035.959961</td>
      <td>746300</td>
      <td>Increase</td>
      <td>1035.479981</td>
      <td>0.959961</td>
    </tr>
    <tr>
      <th>2017-11-24</th>
      <td>1035.869995</td>
      <td>1043.177979</td>
      <td>1035.000000</td>
      <td>1040.609985</td>
      <td>1040.609985</td>
      <td>537000</td>
      <td>Increase</td>
      <td>1038.239990</td>
      <td>4.739990</td>
    </tr>
    <tr>
      <th>2017-11-27</th>
      <td>1040.000000</td>
      <td>1055.459961</td>
      <td>1038.439941</td>
      <td>1054.209961</td>
      <td>1054.209961</td>
      <td>1307900</td>
      <td>Increase</td>
      <td>1047.104981</td>
      <td>14.209961</td>
    </tr>
    <tr>
      <th>2017-11-28</th>
      <td>1055.089966</td>
      <td>1062.375000</td>
      <td>1040.000000</td>
      <td>1047.410034</td>
      <td>1047.410034</td>
      <td>1424400</td>
      <td>Decrease</td>
      <td>1051.250000</td>
      <td>7.679932</td>
    </tr>
    <tr>
      <th>2017-11-29</th>
      <td>1042.680054</td>
      <td>1044.079956</td>
      <td>1015.650024</td>
      <td>1021.659973</td>
      <td>1021.659973</td>
      <td>2459400</td>
      <td>Decrease</td>
      <td>1032.170014</td>
      <td>21.020081</td>
    </tr>
    <tr>
      <th>2017-11-30</th>
      <td>1022.369995</td>
      <td>1028.489990</td>
      <td>1015.000000</td>
      <td>1021.409973</td>
      <td>1021.409973</td>
      <td>1724000</td>
      <td>Decrease</td>
      <td>1021.889984</td>
      <td>0.960022</td>
    </tr>
    <tr>
      <th>2017-12-01</th>
      <td>1015.799988</td>
      <td>1022.489990</td>
      <td>1002.020020</td>
      <td>1010.169983</td>
      <td>1010.169983</td>
      <td>1909600</td>
      <td>Decrease</td>
      <td>1012.984985</td>
      <td>5.630005</td>
    </tr>
    <tr>
      <th>2017-12-04</th>
      <td>1012.659973</td>
      <td>1016.099976</td>
      <td>995.570007</td>
      <td>998.679993</td>
      <td>998.679993</td>
      <td>1906400</td>
      <td>Decrease</td>
      <td>1005.669983</td>
      <td>13.979980</td>
    </tr>
    <tr>
      <th>2017-12-05</th>
      <td>995.940002</td>
      <td>1020.609985</td>
      <td>988.280029</td>
      <td>1005.150024</td>
      <td>1005.150024</td>
      <td>2067300</td>
      <td>Increase</td>
      <td>1000.545013</td>
      <td>9.210022</td>
    </tr>
    <tr>
      <th>2017-12-06</th>
      <td>1001.500000</td>
      <td>1024.969971</td>
      <td>1001.140015</td>
      <td>1018.380005</td>
      <td>1018.380005</td>
      <td>1272000</td>
      <td>Increase</td>
      <td>1009.940002</td>
      <td>16.880005</td>
    </tr>
    <tr>
      <th>2017-12-07</th>
      <td>1020.429993</td>
      <td>1034.239990</td>
      <td>1018.070984</td>
      <td>1030.930054</td>
      <td>1030.930054</td>
      <td>1458200</td>
      <td>Increase</td>
      <td>1025.680024</td>
      <td>10.500061</td>
    </tr>
    <tr>
      <th>2017-12-08</th>
      <td>1037.489990</td>
      <td>1042.050049</td>
      <td>1032.521973</td>
      <td>1037.050049</td>
      <td>1037.050049</td>
      <td>1290800</td>
      <td>Decrease</td>
      <td>1037.270019</td>
      <td>0.439941</td>
    </tr>
    <tr>
      <th>2017-12-11</th>
      <td>1035.500000</td>
      <td>1043.800049</td>
      <td>1032.050049</td>
      <td>1041.099976</td>
      <td>1041.099976</td>
      <td>1192800</td>
      <td>Increase</td>
      <td>1038.299988</td>
      <td>5.599976</td>
    </tr>
    <tr>
      <th>2017-12-12</th>
      <td>1039.630005</td>
      <td>1050.310059</td>
      <td>1033.689941</td>
      <td>1040.479980</td>
      <td>1040.479980</td>
      <td>1279500</td>
      <td>Increase</td>
      <td>1040.054993</td>
      <td>0.849975</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2017-12-19</th>
      <td>1075.199951</td>
      <td>1076.839966</td>
      <td>1063.550049</td>
      <td>1070.680054</td>
      <td>1070.680054</td>
      <td>1338700</td>
      <td>Decrease</td>
      <td>1072.940002</td>
      <td>4.519897</td>
    </tr>
    <tr>
      <th>2017-12-20</th>
      <td>1071.780029</td>
      <td>1073.380005</td>
      <td>1061.520020</td>
      <td>1064.949951</td>
      <td>1064.949951</td>
      <td>1268600</td>
      <td>Decrease</td>
      <td>1068.364990</td>
      <td>6.830078</td>
    </tr>
    <tr>
      <th>2017-12-21</th>
      <td>1064.949951</td>
      <td>1069.329956</td>
      <td>1061.793945</td>
      <td>1063.630005</td>
      <td>1063.630005</td>
      <td>995700</td>
      <td>Decrease</td>
      <td>1064.289978</td>
      <td>1.319946</td>
    </tr>
    <tr>
      <th>2017-12-22</th>
      <td>1061.109985</td>
      <td>1064.199951</td>
      <td>1059.439941</td>
      <td>1060.119995</td>
      <td>1060.119995</td>
      <td>755100</td>
      <td>Decrease</td>
      <td>1060.614990</td>
      <td>0.989990</td>
    </tr>
    <tr>
      <th>2017-12-26</th>
      <td>1058.069946</td>
      <td>1060.119995</td>
      <td>1050.199951</td>
      <td>1056.739990</td>
      <td>1056.739990</td>
      <td>760600</td>
      <td>Decrease</td>
      <td>1057.404968</td>
      <td>1.329956</td>
    </tr>
    <tr>
      <th>2017-12-27</th>
      <td>1057.390015</td>
      <td>1058.369995</td>
      <td>1048.050049</td>
      <td>1049.369995</td>
      <td>1049.369995</td>
      <td>1271900</td>
      <td>Decrease</td>
      <td>1053.380005</td>
      <td>8.020020</td>
    </tr>
    <tr>
      <th>2017-12-28</th>
      <td>1051.599976</td>
      <td>1054.750000</td>
      <td>1044.770020</td>
      <td>1048.140015</td>
      <td>1048.140015</td>
      <td>837100</td>
      <td>Decrease</td>
      <td>1049.869995</td>
      <td>3.459961</td>
    </tr>
    <tr>
      <th>2017-12-29</th>
      <td>1046.719971</td>
      <td>1049.699951</td>
      <td>1044.900024</td>
      <td>1046.400024</td>
      <td>1046.400024</td>
      <td>887500</td>
      <td>Decrease</td>
      <td>1046.559998</td>
      <td>0.319947</td>
    </tr>
    <tr>
      <th>2018-01-02</th>
      <td>1048.339966</td>
      <td>1066.939941</td>
      <td>1045.229980</td>
      <td>1065.000000</td>
      <td>1065.000000</td>
      <td>1237600</td>
      <td>Increase</td>
      <td>1056.669983</td>
      <td>16.660034</td>
    </tr>
    <tr>
      <th>2018-01-03</th>
      <td>1064.310059</td>
      <td>1086.290039</td>
      <td>1063.209961</td>
      <td>1082.479980</td>
      <td>1082.479980</td>
      <td>1430200</td>
      <td>Increase</td>
      <td>1073.395019</td>
      <td>18.169921</td>
    </tr>
    <tr>
      <th>2018-01-04</th>
      <td>1088.000000</td>
      <td>1093.569946</td>
      <td>1084.001953</td>
      <td>1086.400024</td>
      <td>1086.400024</td>
      <td>1004600</td>
      <td>Decrease</td>
      <td>1087.200012</td>
      <td>1.599976</td>
    </tr>
    <tr>
      <th>2018-01-05</th>
      <td>1094.000000</td>
      <td>1104.250000</td>
      <td>1092.000000</td>
      <td>1102.229980</td>
      <td>1102.229980</td>
      <td>1279100</td>
      <td>Increase</td>
      <td>1098.114990</td>
      <td>8.229980</td>
    </tr>
    <tr>
      <th>2018-01-08</th>
      <td>1102.229980</td>
      <td>1111.270020</td>
      <td>1101.619995</td>
      <td>1106.939941</td>
      <td>1106.939941</td>
      <td>1047600</td>
      <td>Increase</td>
      <td>1104.584961</td>
      <td>4.709961</td>
    </tr>
    <tr>
      <th>2018-01-09</th>
      <td>1109.400024</td>
      <td>1110.569946</td>
      <td>1101.230957</td>
      <td>1106.260010</td>
      <td>1106.260010</td>
      <td>902500</td>
      <td>Decrease</td>
      <td>1107.830017</td>
      <td>3.140014</td>
    </tr>
    <tr>
      <th>2018-01-10</th>
      <td>1097.099976</td>
      <td>1104.599976</td>
      <td>1096.109985</td>
      <td>1102.609985</td>
      <td>1102.609985</td>
      <td>1042800</td>
      <td>Increase</td>
      <td>1099.854981</td>
      <td>5.510009</td>
    </tr>
    <tr>
      <th>2018-01-11</th>
      <td>1106.300049</td>
      <td>1106.525024</td>
      <td>1099.589966</td>
      <td>1105.520020</td>
      <td>1105.520020</td>
      <td>978300</td>
      <td>Decrease</td>
      <td>1105.910034</td>
      <td>0.780029</td>
    </tr>
    <tr>
      <th>2018-01-12</th>
      <td>1102.410034</td>
      <td>1124.290039</td>
      <td>1101.150024</td>
      <td>1122.260010</td>
      <td>1122.260010</td>
      <td>1720500</td>
      <td>Increase</td>
      <td>1112.335022</td>
      <td>19.849976</td>
    </tr>
    <tr>
      <th>2018-01-16</th>
      <td>1132.510010</td>
      <td>1139.910034</td>
      <td>1117.832031</td>
      <td>1121.760010</td>
      <td>1121.760010</td>
      <td>1575300</td>
      <td>Decrease</td>
      <td>1127.135010</td>
      <td>10.750000</td>
    </tr>
    <tr>
      <th>2018-01-17</th>
      <td>1126.219971</td>
      <td>1132.599976</td>
      <td>1117.010010</td>
      <td>1131.979980</td>
      <td>1131.979980</td>
      <td>1202600</td>
      <td>Increase</td>
      <td>1129.099976</td>
      <td>5.760009</td>
    </tr>
    <tr>
      <th>2018-01-18</th>
      <td>1131.410034</td>
      <td>1132.510010</td>
      <td>1117.500000</td>
      <td>1129.790039</td>
      <td>1129.790039</td>
      <td>1198200</td>
      <td>Decrease</td>
      <td>1130.600036</td>
      <td>1.619995</td>
    </tr>
    <tr>
      <th>2018-01-19</th>
      <td>1131.829956</td>
      <td>1137.859985</td>
      <td>1128.300049</td>
      <td>1137.510010</td>
      <td>1137.510010</td>
      <td>1778200</td>
      <td>Increase</td>
      <td>1134.669983</td>
      <td>5.680054</td>
    </tr>
    <tr>
      <th>2018-01-22</th>
      <td>1137.489990</td>
      <td>1159.880005</td>
      <td>1135.109985</td>
      <td>1155.810059</td>
      <td>1155.810059</td>
      <td>1618000</td>
      <td>Increase</td>
      <td>1146.650024</td>
      <td>18.320069</td>
    </tr>
    <tr>
      <th>2018-01-23</th>
      <td>1159.849976</td>
      <td>1171.626953</td>
      <td>1158.750000</td>
      <td>1169.969971</td>
      <td>1169.969971</td>
      <td>1333100</td>
      <td>Increase</td>
      <td>1164.909973</td>
      <td>10.119995</td>
    </tr>
    <tr>
      <th>2018-01-24</th>
      <td>1177.329956</td>
      <td>1179.859985</td>
      <td>1161.050049</td>
      <td>1164.239990</td>
      <td>1164.239990</td>
      <td>1416600</td>
      <td>Decrease</td>
      <td>1170.784973</td>
      <td>13.089966</td>
    </tr>
    <tr>
      <th>2018-01-25</th>
      <td>1172.530029</td>
      <td>1175.939941</td>
      <td>1162.760010</td>
      <td>1170.369995</td>
      <td>1170.369995</td>
      <td>1480500</td>
      <td>Decrease</td>
      <td>1171.450012</td>
      <td>2.160034</td>
    </tr>
    <tr>
      <th>2018-01-26</th>
      <td>1175.079956</td>
      <td>1175.839966</td>
      <td>1158.109985</td>
      <td>1175.839966</td>
      <td>1175.839966</td>
      <td>2018800</td>
      <td>Increase</td>
      <td>1175.459961</td>
      <td>0.760010</td>
    </tr>
    <tr>
      <th>2018-01-29</th>
      <td>1176.479980</td>
      <td>1186.890015</td>
      <td>1171.979980</td>
      <td>1175.579956</td>
      <td>1175.579956</td>
      <td>1378900</td>
      <td>Decrease</td>
      <td>1176.029968</td>
      <td>0.900024</td>
    </tr>
    <tr>
      <th>2018-01-30</th>
      <td>1167.829956</td>
      <td>1176.520020</td>
      <td>1163.520020</td>
      <td>1163.689941</td>
      <td>1163.689941</td>
      <td>1556300</td>
      <td>Decrease</td>
      <td>1165.759949</td>
      <td>4.140015</td>
    </tr>
    <tr>
      <th>2018-01-31</th>
      <td>1170.569946</td>
      <td>1173.000000</td>
      <td>1159.130005</td>
      <td>1169.939941</td>
      <td>1169.939941</td>
      <td>1538700</td>
      <td>Decrease</td>
      <td>1170.254944</td>
      <td>0.630005</td>
    </tr>
    <tr>
      <th>2018-02-01</th>
      <td>1162.609985</td>
      <td>1174.000000</td>
      <td>1157.520020</td>
      <td>1167.699951</td>
      <td>1167.699951</td>
      <td>2412100</td>
      <td>Increase</td>
      <td>1165.154968</td>
      <td>5.089966</td>
    </tr>
  </tbody>
</table>
<p>64 rows × 9 columns</p>
</div>

In [5]:
from bokeh.models import Title

p = figure(title="A", x_axis_type='datetime', width=1000, height=300)

p.grid.grid_line_alpha=0.3

hours_12=12*60*60*1000

p.segment(df.index, df.High, df.index, df.Low, color="Black")

p.rect(df.index[df.Status=="Increase"], df.Middle[df.Status=="Increase"], 
       hours_12, df.Height[df.Status=="Increase"], fill_color="green", line_color="black")

p.rect(df.index[df.Status=="Decrease"], df.Middle[df.Status=="Decrease"], 
       hours_12, df.Height[df.Status=="Decrease"], fill_color="red", line_color="black")

output_file("CS.html")
show(p)